#!/bin/bash
#SBATCH --job-name=vidor-tgm
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --ntasks-per-node=1
#SBATCH --time=20:00:00
#SBATCH --mem=60000M
#SBATCH --partition=gpu_shared
#SBATCH --gres=gpu:1
module purge
module load 2019
module load cuDNN/7.4.2-CUDA-10.0.130  
module load eb
source activate VAD
export LD_LIBRARY_PATH=/hpc/eb/Debian9/cuDNN/7.4.2-CUDA-10.0.130/lib64:$LD_LIBRARY_PATH
srun python3 train_tgm.py
 